change-id = 118724

[llvm]
download-ci-llvm = false
targets = "AArch64;X86"

[build]
target = [
    "aarch64-apple-darwin",
    "x86_64-unknown-none",
]
optimized-compiler-builtins = true

[rust]
llvm-tools = true
lld = true
